uhu: Explicitly pass libarchive.so.13 path to uhu
If we don't pass libarchive.so absolute path, python3 tries to find the
libarchive.so.13 in the host system, and fails with error:

  AttributeError: python3: undefined symbol: archive_errno

Use LIBARCHIVE to make sure python3 is looking into native sysroot to
find libarchive.so

Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
(cherry picked from commit 023f74e5b1414ef6b40b5ce147b9a101b0a662c7)